language: python
install: skip
script: python ./src/hello.py < answer.txt
arch: ppc64le
jobs:
  include:
     - os: linux
       dist: focal
       arch: arm64-graviton2
       virt: vm
       group: edge
     - os: freebsd
       arch: arm64-graviton2
       virt: lxd
       group: edge
    - os: windows
      language: sh
      python: "3.7"       
     - os: linux
       arch: arm64 # ARMv8
       dist: bionic
       language: python
       python: "3.6"
       before_install:
         - kerl list installations
         - uname -r 
     - dist: focal
       before_install:
         - cmake --version
         - git --version
         - git --help
         - hg --version
         - svn --version
         - clang --version
         - llvm-config --version
         - choco install python3
         - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
         - virtualenv $HOME/venv
         - source $HOME/venv/Scripts/activate
#     - dist: focal
#       services: mongodb
#       script: mongod --version
#    - dist: focal
#      services:
#        - redis
#        - mysql
#    - dist: focal
#      addons:
#        apt:
#          sources:
#            - sourceline: "deb https://repo.mongodb.org/apt/ubuntu $(lsb_release -cs)/mongodb-org/4.4 multiverse"
#          packages:
#            - mongodb
#    - dist: focal
#      python: "2.7"
#    - dist: focal
#      python: "3.6"
#   - os: linux
#     arch: arm64 # ARMv8
#     language: python
#     python: "2.7"
#     dist: xenial
